# Generated by Django 3.1 on 2023-05-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit_foodie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nutrients',
            table='nutrients',
        ),
    ]
