# Generated by Django 3.1 on 2023-05-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit_foodie', '0002_auto_20230509_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrients',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fit_foodie.accounts'),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='fname',
            field=models.CharField(max_length=100),
        ),
    ]
