# Generated by Django 3.1 on 2023-05-09 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit_foodie', '0003_auto_20230510_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrients',
            name='u_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fit_foodie.accounts'),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='fid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
