# Generated by Django 3.1 on 2023-05-09 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fit_foodie', '0004_auto_20230510_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrients',
            name='u_id',
        ),
    ]
