# Generated by Django 3.1 on 2023-05-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_foodie', '0005_remove_nutrients_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrients',
            name='fid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
